---
version: "3"

services:
  nginx:
    image: nginx:1.25.2-bookworm
    container_name: nginx
    environment:
      - TZ=America/Toronto
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - 123_network
      - 456_network
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  123_network:
    external: true
  456_network:
    external: true
